. .\mcPSFunctions.ps1

<# Examples..
$appName= 'WinZip'
$appVer = '2.0.1'
$msiparams = "/qn ADDDESKTOPICON=0 ADDMENUGROUP=0 ADDSTARTMENU=1 DISABLECLOUDSERVICES=ALL DISABLENOTIFICATIONSERVICES=ALL DISABLESETTINGSFROMCLOUD=1 INSTALLBACKGROUNDTOOLS=0 INSTALLAMAZONS3=0 INSTALLBOX=0 INSTALLCLOUDME=0 INSTALLDROPBOX=0 INSTALLFTP=0 INSTALLGOOGLEDRIVE=0 INSTALLMEDIAFIRE=0 INSTALLOFFICE365=0 INSTALLONEDRIVE=0 INSTALLSHAREPOINT=0 INSTALLSUGARSYNC=0 INSTALLZIPSHARE=0 INSTALLJOBFILES=0 INSTALLSCANNERS=0 INSTALLUPDATENOTIFIER=0 INST_QKPICK=0 RUNWINZIP=0 SHOW_WEBPAGE=0 USAGE_COLLECT=0 USAGEPICK=Usage_No DISABLEMM=1 DISABLEZIPANDSHARE=1 ENABLEEXPRESSFEATURES=0 INSTALLEXPRESSOFFICE=0 USAGECOLLECTLOCK=1"
#>

install-MSI -appInstaller "winzip210mulent-64.msi" -arguments $msiparams -appName $appName -appVer $appVer
